<?php

// SPDX-License-Identifier: Apache-2.0

declare(strict_types=1);

namespace App\Install;

/**
 * RH-4.3 (ADR-0070) — generate the "Option B" web-subdir artifacts for a subdirectory install on a host that
 * FORBIDS a full web-root symlink.
 *
 * It writes, into the web-visible subdir (e.g. ~/public_html/community), a thin `index.php` stub that boots
 * the app from OUTSIDE the web root, an `.htaccess` carrying `RewriteBase /community/`, and `build/` +
 * `storage/` links back to the app's SINGLE canonical trees (symlink, with a recursive-copy fallback). Because
 * `build/` points at the one `public/build`, a rebuild can never desync the served assets from the Vite
 * manifest (G2); because the app boots under `/community`, the request base path (SCRIPT_NAME) is correct, so
 * the base-path detector and Livewire work without drift.
 *
 * Idempotent — safe to re-run after a deploy. Option A (a full `public/` symlink) needs none of this; this is
 * the no-symlink fallback (G3).
 */
class SubdirectoryScaffold
{
    /**
     * @param  string  $webDir  absolute path to the web-visible subdir (e.g. /home/you/public_html/community)
     * @param  string|null  $basePath  URL subpath (e.g. "/community"); defaults to "/".basename($webDir)
     * @param  string|null  $appPublic  the app's public/ dir; defaults to public_path() (override for tests)
     * @return array<string,string> per-artifact result: written | symlink | copy | failed
     */
    public function scaffold(string $webDir, ?string $basePath = null, ?string $appPublic = null): array
    {
        $webDir = rtrim(str_replace('\\', '/', $webDir), '/');
        $appPublic = rtrim(str_replace('\\', '/', $appPublic ?? public_path()), '/');
        $base = $this->normaliseBase($basePath ?? '/'.basename($webDir));

        if (! is_dir($webDir)) {
            @mkdir($webDir, 0755, true);
        }

        return [
            'index.php' => $this->writeStub($webDir, $appPublic),
            '.htaccess' => $this->writeHtaccess($webDir, $appPublic, $base),
            'build' => $this->link($appPublic.'/build', $webDir.'/build'),
            'storage' => $this->link($this->storageSource(), $webDir.'/storage'),
        ];
    }

    /** Normalise a URL subpath to a leading-slash, no-trailing-slash form ("/community"); "" for the root. */
    public function normaliseBase(string $base): string
    {
        $base = '/'.trim(str_replace('\\', '/', $base), '/');

        return $base === '/' ? '' : $base;
    }

    private function writeStub(string $webDir, string $appPublic): string
    {
        $target = $appPublic.'/index.php';
        $stub = <<<PHP
        <?php

        /*
         * NovFora subdirectory front controller (RH-4 Option B — GENERATED by `php artisan novfora:subdir:scaffold`).
         * Boots the app from OUTSIDE this web root so a single canonical codebase, build/ and storage/ are served.
         * Re-run the command after moving the app or deploying a new release.
         */

        require '{$target}';

        PHP;

        return file_put_contents($webDir.'/index.php', $stub) !== false ? 'written' : 'failed';
    }

    private function writeHtaccess(string $webDir, string $appPublic, string $base): string
    {
        $source = $appPublic.'/.htaccess';
        $rules = is_file($source) ? (string) file_get_contents($source) : $this->defaultHtaccess();

        $directive = 'RewriteBase '.($base === '' ? '/' : $base.'/');

        if (preg_match('/^\s*RewriteBase\b/mi', $rules)) {
            // Replace an existing RewriteBase so re-running with a different subpath stays correct.
            $rules = preg_replace('/^\s*RewriteBase\b.*$/mi', $directive, $rules, 1);
        } elseif (preg_match('/^\s*RewriteEngine\s+On\b/mi', $rules)) {
            // Insert the base immediately after `RewriteEngine On` (where Apache expects it).
            $rules = preg_replace('/^(\s*RewriteEngine\s+On\b.*)$/mi', "$1\n    {$directive}", (string) $rules, 1);
        } else {
            $rules = "<IfModule mod_rewrite.c>\n    RewriteEngine On\n    {$directive}\n</IfModule>\n".$rules;
        }

        return file_put_contents($webDir.'/.htaccess', $rules) !== false ? 'written' : 'failed';
    }

    /** The canonical uploads source that public/storage points at — served under /community/storage/... */
    private function storageSource(): string
    {
        return rtrim(str_replace('\\', '/', (string) config('novfora.storage.public_source', storage_path('app/public'))), '/');
    }

    /**
     * Link $link -> $source (symlink first; recursive copy fallback on hosts that forbid symlinks). Returns
     * "symlink" | "copy" | "failed". Existing correct symlinks are left in place (idempotent).
     */
    private function link(string $source, string $link): string
    {
        if (! file_exists($source)) {
            return 'failed';
        }

        if (is_link($link)) {
            if (@readlink($link) === $source) {
                return 'symlink';
            }
            @unlink($link);
        }

        if (! file_exists($link) && @symlink($source, $link)) {
            return 'symlink';
        }

        return $this->copyMirror($source, $link) ? 'copy' : 'failed';
    }

    private function copyMirror(string $source, string $dest): bool
    {
        if (! is_dir($source)) {
            return false;
        }
        if (! is_dir($dest) && ! @mkdir($dest, 0755, true) && ! is_dir($dest)) {
            return false;
        }

        $items = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($source, \FilesystemIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::SELF_FIRST
        );

        foreach ($items as $item) {
            /** @var \SplFileInfo $item */
            $relative = substr($item->getPathname(), strlen($source) + 1);
            $targetPath = $dest.'/'.str_replace('\\', '/', $relative);

            if ($item->isDir()) {
                if (! is_dir($targetPath)) {
                    @mkdir($targetPath, 0755, true);
                }
            } else {
                @copy($item->getPathname(), $targetPath);
            }
        }

        return true;
    }

    private function defaultHtaccess(): string
    {
        return <<<'HTACCESS'
        <IfModule mod_rewrite.c>
            <IfModule mod_negotiation.c>
                Options -MultiViews -Indexes
            </IfModule>

            RewriteEngine On

            # Handle Authorization Header
            RewriteCond %{HTTP:Authorization} .
            RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

            # Send Requests To Front Controller...
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^ index.php [L]
        </IfModule>

        HTACCESS;
    }
}
